// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsEhRmN1WlakcNnzLMpbXSeDkckBs4a6s',
    appId: '1:721450526925:web:e9a6b1bd6f6b8800d72184',
    messagingSenderId: '721450526925',
    projectId: 'recipe-47cf3',
    authDomain: 'recipe-47cf3.firebaseapp.com',
    storageBucket: 'recipe-47cf3.firebasestorage.app',
    measurementId: 'G-NQG5TQP9E1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGnOF4WK3_nIMYKnY_kSvFMcKACQxEEsQ',
    appId: '1:721450526925:android:6c177d91a814e84cd72184',
    messagingSenderId: '721450526925',
    projectId: 'recipe-47cf3',
    storageBucket: 'recipe-47cf3.firebasestorage.app',
  );
}
